# Base image which contains python environment for creating rag content
ARG BYOK_TOOL_IMAGE=registry.redhat.io/openshift-lightspeed-tech-preview/lightspeed-rag-tool-rhel9:latest

# Final image to which the created rag db will be copied
ARG UBI_BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal

# STAGE 1: Take the downloaded html docs as input and run through stripping, chunking and embedding
FROM ${BYOK_TOOL_IMAGE} as tool
# we are expecting the downloaded html in this folder
ARG VECTOR_DB
ARG DOC_SLUG=red_hat_openshift_data_foundation
RUN dnf -y install make && dnf clean all
WORKDIR /workdir
COPY scripts/doc_downloader scripts/html_chunking scripts/html_embeddings scripts/
COPY odf/Makefile odf/
COPY odf/${DOC_SLUG} odf/
# On a 8 core vCPU with AVX2 this command took 1hr45min
RUN make -C odf create-rag
COPY vector_db vector_db

# STAGE 2: Copy the embedded rag folder from STAGE 1
FROM ${UBI_BASE_IMAGE}
COPY --from=tool /workdir/vector_db /rag/vector_db
